### ISSUE TITLE
Many Oracle types are not supported

### ISSUE THREAD

**Issue by object** [flq/Simple.Data.Oracle#1]
I tried to use the provider with a sample database and got a problem with NVARCHAR2 data type. I can see that there are only few types supported. This page provides pretty good overview of mapping between Oracle types and CRL:

http://www.devart.com/dotconnect/oracle/docs/DataTypeMapping.html

If you want I can extend the provider with other types. Let me know.

**Comment by flq** [comment]
Hi,
this provider needs a bag of attention, I need to push it up against the newest Simple.Data version. If you want to provide the additional mappings, that'd be great! Just fork & branch & send me a pull request :)

**Comment by object** [comment]
OK, will do!

**Comment by object** [comment]
I see that you are currently upgrading Oracle provider. I was going to branch the project to add Devart dotConnect support. Should I wait until Master is merged with Upgrade to do my changes to the most recent code, or should I branch from Upgrade?

**Comment by flq** [comment]
Hi there, please branch from upgrade as I would like to incorporate your additions to the next release.

**Comment by flq** [comment]
Closing, as there is a pull request for that
