### ISSUE TITLE
Support for multiple schema's

### ISSUE THREAD

**Issue by sooey** [flq/Simple.Data.Oracle#11]
Currently I'm using the appsetting below in my config to access the needed schema in oracle:

key="Simple.Data.Oracle.Schema" value="XYZ"

This works for a single schema but I need to query data in a single oracle database but across many schema's. How do I do this?

FYI - I've tried db.schema-name.table-name.FindBy... but this only works when my schema-name matches the one set in my config. I've also removed the config setting and tried the syntax above with no success.

**Comment by flq** [comment]
Hello there,
I am currently not the maintainer of this project - The last Nuget has been built from the repository over here: https://github.com/SimonH/Simple.Data.Oracle
