### ISSUE TITLE
Not able to run the query against Oracle database

### ISSUE THREAD

**Issue by vrvivekanandhan** [flq/Simple.Data.Oracle#12]
Hello,
I am trying to connect to both MS Sql server and Oracle database in my application.

I am able to connect to ms sql server and get the results but i am not able to get the results from Oracle db.

The code in my class library is pasted below
public class ProductOneBL
    {  
        dynamic ProductOneDBSQLServer = Database.Opener.OpenConnection(ConnectionStrings.CurrentSqlEnvironment, "System.Data.SqlClient");
        dynamic ProductOneDBOracle = Database.Opener.OpenConnection(ConnectionStrings.CurrentOracleEnvironment, "Oracle.DataAccess.Client");

```
    public User GetUserInformation(string Identity)
    {
        User user = ProductOneDBSQLServer.User.FindByIdentity(Identity);
        return user;
    }


    public User GetUserInformation2(string Identity)
    {
        User user = ProductOneDBOracle.user_test.FindByIdentity(Identity);
        return user;
    }

}
```

The first function GetUserInformation works fine and gets the results from MS SQL server.
The second function GetUserInformation2 runs without any error or exception but it keeps on running and i am not getting results back.(waited for more than 10 mins)

I have installed following nuget packages:
1. Simple.Data 0.18.3.1
2. Simple.Data.Ado 0.18.3.1
3. Simple.Data.Oracle 0.18.0.0
4. Simple.Data.SqlServer 0.18.3.1

and also installed ODP.net(Oracle.DataAccess 4.112.2.0) and its available in the below path of my machine
C:\app\350941\product\11.2.0\client_1\odp.net\bin\4

I have connected to this oracle database by using OracleConnection and OracleCommand object and got the results in a datareader. It is not working when i use Simple.data.

Please provide ur suggestions.Thanks!!

Regards,
Vivek

**Comment by flq** [comment]
Hello there,
I am currently not the maintainer of this project - The last Nuget has been built from the repository over here: https://github.com/SimonH/Simple.Data.Oracle
