### ISSUE TITLE
FK constraints owner must be current user or SQL Reflection fails

### ISSUE THREAD

**Issue by mborizanov** [flq/Simple.Data.Oracle#13]
We have a project where the current user is not the owner of the schema. As a result of that we get errors when trying to join tables:

```
Simple.Data.Ado.SchemaResolutionException : Could not join 'TABLE_A' and 'TABLE_B'.
```

This is caused by the following SQL from `table_fks.txt` which uses `user_constraints` and `user_cons_columns`.

```
select con.table_name as fk_table, con.column_name as fk_column,
       rel.table_name as pk_table, rel.column_name as pk_column
from user_cons_columns con 
    join user_constraints cc 
      on con.constraint_name = cc.constraint_name
    join user_cons_columns rel 
      on cc.r_constraint_name = rel.constraint_name 
     and con.position = rel.position
where
    cc.constraint_type = 'R'
```

Perhaps this could use `all_constraints` and `all_cons_columns` but then filter by `all_cons_columns.OWNER` using the schema name. 

In our case, we have overriden the schema name using `Simple.Data.Oracle.Schema` in the `app.config`.

**Comment by flq** [comment]
Hello there,
I am currently not the maintainer of this project - The last Nuget has been built from the repository over here: https://github.com/SimonH/Simple.Data.Oracle
