### ISSUE TITLE
Incorrect order of retrieved table columns

### ISSUE THREAD

**Issue by object** [flq/Simple.Data.Oracle#6]
One of the failed unit tests (in upgrade branch) is caused by incorrect column order:

Test 'Simple.Data.Oracle.Tests.ObtainingTableMetadata.found_columns_to_employees' failed: 
  Expected string length 6 but was 5. Strings differ at index 0.
  Expected: "JOB_ID"
  But was:  "EMAIL"
  -----------^
    ObtainingTableMetadata.cs(46,0): at Simple.Data.Oracle.Tests.ObtainingTableMetadata.found_columns_to_employees()

The expected column should JOB_ID. However when column informations is retrieved using SQL reflection, the columns in the result set are not ordered, so they can be expected in any order.

Perhaps this works differently in Oracle Express and Standard edition, but to ensure columns are properly ordered the SQL statement should include ORDER BY clause.

**Comment by flq** [comment]
Rewritten test to not expect a column order
